version: '3.8'

services:
  loki-log-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOKI_URL=http://loki:3100
      - SLACK_TOKEN=${SLACK_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - VERBOSE_LOGGING=true
      - POLL_SECONDS=1
    # volumes:
    #   - ./custom-query.logql:/data/query
    restart: unless-stopped
    depends_on:
      - loki
    networks:
      - loki-network

  # Example Loki service - replace with your actual Loki setup
  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki-network

networks:
  loki-network:
    driver: bridge 